const GROUPS = [
  {
    id: 'identity',
    name: 'Identity',
    color: '#8fe6ff',
    summary: ['timestamp', 'close', 'is_bullish'],
    features: [
      'timestamp',
      'open',
      'high',
      'low',
      'close',
    ],
  },
  {
    id: 'structure',
    name: 'Structure',
    color: '#ff6b8f',
    summary: ['is_swing_high', 'is_swing_low', 'bos_bull', 'bos_bear', 'choch'],
    features: [
      'is_swing_high',
      'is_swing_low',
      'dist_swing_high',
      'dist_swing_low',
      'swing_had_break',
      'chain_depth',
      'prev_swing_features',
      'cluster_range',
      'cluster_range_atr',
      'cluster_spread',
    ],
  },
  {
    id: 'break_quality',
    name: 'Break Quality',
    color: '#ffb347',
    summary: ['bos_body', 'bos_wick', 'break_depth', 'breaks_highs', 'breaks_lows'],
    features: [
      'bos_bull',
      'bos_bear',
      'choch',
      'bos_body',
      'bos_wick',
      'break_depth',
      'swing_age',
      'broken_swing_ts',
      'swing_age_norm',
      'breaks_highs',
      'breaks_lows',
      'max_age_broken',
      'min_age_broken',
      'sw_body_ratio',
      'sw_wick_ratio',
      'sw_delta_pct',
      'sw_vol_rel',
      'sw_bullish',
      'sw_body_pos',
      'sw_ohlc',
      'vol_ratio_bsw',
      'delta_ratio_bsw',
      'body_ratio_bsw',
      'same_dir',
      'broken_was_seeker',
      'broken_was_seeker_div',
    ],
  },
  {
    id: 'divergence',
    name: 'Divergence',
    color: '#b388ff',
    summary: ['bull_div', 'bear_div', 'bull_div_streak', 'bear_div_streak', 'div_strength'],
    features: [
      'macd_line',
      'macd_peak',
      'macd_trough',
      'bull_div',
      'bear_div',
      'div_near_daily',
      'div_strength',
      'div_width',
      'bull_div_streak',
      'bear_div_streak',
    ],
  },
  {
    id: 'seeker',
    name: 'Seeker',
    color: '#5cffb0',
    summary: ['is_seeker_hs', 'is_seeker_ls', 'is_seeker_div_hs', 'is_seeker_div_ls', 'is_seeker_kill'],
    features: [
      'is_seeker_hs',
      'is_seeker_ls',
      'is_seeker_div',
      'is_seeker_div_hs',
      'is_seeker_div_ls',
      'seeker_div_nr',
      'dist_prev_seeker_div',
      'dist_prev_seeker_div_norm',
      'is_seeker_kill',
      'killed_seeker_divs',
      'killed_seeker_ts',
      'killed_seekers_count',
      'killed_seekers_ages',
      'killed_seekers_oldest_ts',
      'killed_seekers_newest_ts',
      'killed_seekers_span_bars',
      'killed_seekers_age_min',
      'killed_seekers_age_max',
      'killed_seekers_age_avg',
      'candle_was_seeker',
      'candle_was_seeker_div',
      'seeker_zone_top',
      'seeker_zone_bottom',
      'seeker_zone_size',
      'seeker_zone_pct_of_range',
      'seeker_zone_vs_body',
      'seeker_wick_dominance',
    ],
  },
  {
    id: 'flow',
    name: 'Flow',
    color: '#00e0a8',
    summary: ['volume', 'delta', 'vol_vs_ma', 'futures_minus_spot_volume', 'futures_minus_spot_delta'],
    features: [
      'volume',
      'delta',
      'spot_volume',
      'spot_delta',
      'futures_volume',
      'futures_delta',
      'futures_minus_spot_volume',
      'futures_minus_spot_delta',
      'delta_pct',
      'vol_vs_ma',
      'delta_vs_ma',
    ],
  },
  {
    id: 'candle_shape',
    name: 'Candle Shape',
    color: '#4fd5ff',
    summary: ['body_ratio', 'wick_ratio', 'body_position', 'is_bullish'],
    features: [
      'body_size',
      'upper_wick',
      'lower_wick',
      'total_range',
      'body_ratio',
      'wick_ratio',
      'body_position',
      'is_bullish',
    ],
  },
  {
    id: 'context_trend',
    name: 'Context/Trend',
    color: '#a4c2ff',
    summary: ['ema21_dist', 'ema50_dist', 'ema200_dist', 'rsi14'],
    features: [
      'ema21_dist',
      'ema50_dist',
      'ema200_dist',
      'atr14',
      'rsi14',
      'vwap_dist',
    ],
  },
  {
    id: 'htf',
    name: 'HTF',
    color: '#74b9ff',
    summary: ['htf_trend', 'htf_bos'],
    features: [
      'htf_trend',
      'htf_swing_high',
      'htf_swing_low',
      'htf_bos',
    ],
  },
  {
    id: 'whale',
    name: 'Whale',
    color: '#ff6bd6',
    summary: ['whale_sentiment', 'whale_confidence', 'elite_whale_active'],
    features: [
      'whale_sentiment',
      'whale_confidence',
      'bull_pressure',
      'bear_pressure',
      'whale_cluster',
      'whale_cluster_strength',
      'whale_cluster_dir',
      'elite_whale_active',
    ],
  },
]

export default GROUPS

export const featureToGroup = {}
for (const group of GROUPS) {
  for (const feature of group.features) {
    featureToGroup[feature] = group
  }
}

export const ALL_FEATURE_NAMES = GROUPS.flatMap(group => group.features)

export const CONTEXT_LABELS = {
  meta: { label: 'Meta-Kerze', color: '#ffaa00' },
  swing: { label: 'Swing-Kerze', color: '#ff3355' },
  pair: { label: 'Vergleich', color: '#aa44ff' },
  chain: { label: 'Kette', color: '#556677' },
  cluster: { label: 'Cluster', color: '#556677' },
  general: { label: 'Markt', color: '#556677' },
}

export const FEATURE_META = {
  bos_bull: { desc: 'Bullischer Structure Break auf dieser Kerze.', tier: 1, context: 'meta' },
  bos_bear: { desc: 'Bärischer Structure Break auf dieser Kerze.', tier: 1, context: 'meta' },
  choch: { desc: 'Change of Character auf dieser Kerze.', tier: 1, context: 'meta' },
  bull_div: { desc: 'Bullische Dumb-Money-MACD-Divergenz.', tier: 1, context: 'general' },
  bear_div: { desc: 'Bärische Dumb-Money-MACD-Divergenz.', tier: 1, context: 'general' },
  is_seeker_hs: { desc: 'Kerze ist Ursprung eines High-Seeker-Zyklus.', tier: 1, context: 'meta' },
  is_seeker_ls: { desc: 'Kerze ist Ursprung eines Low-Seeker-Zyklus.', tier: 1, context: 'meta' },
  is_seeker_div_hs: { desc: 'Kerze ist Divergenz auf einem High-Seeker-Zyklus.', tier: 1, context: 'meta' },
  is_seeker_div_ls: { desc: 'Kerze ist Divergenz auf einem Low-Seeker-Zyklus.', tier: 1, context: 'meta' },
  is_seeker_kill: { desc: 'Kerze killt einen oder mehrere offene Seeker-Zyklen.', tier: 1, context: 'meta' },
  vol_vs_ma: { desc: 'Volumen relativ zum lokalen Durchschnitt.', tier: 1, context: 'meta' },
  futures_minus_spot_volume: { desc: 'Futures-Volumen minus Spot-Volumen.', tier: 2, context: 'meta' },
  futures_minus_spot_delta: { desc: 'Futures-Delta minus Spot-Delta.', tier: 2, context: 'meta' },
  seeker_zone_size: { desc: 'Größe der zugrunde liegenden Seeker-Zone.', tier: 2, context: 'meta' },
  seeker_zone_vs_body: { desc: 'Zonengröße relativ zur Body-Größe.', tier: 2, context: 'meta' },
  seeker_wick_dominance: { desc: 'Dominanter Zieldocht relativ zum Gegendocht.', tier: 2, context: 'meta' },
  whale_sentiment: { desc: 'Aggregierte Whale-Richtung für diese Kerze.', tier: 2, context: 'general' },
}

export const TIER1_FEATURES = Object.entries(FEATURE_META).filter(([, meta]) => meta.tier === 1).map(([feature]) => feature)
export const TIER2_FEATURES = Object.entries(FEATURE_META).filter(([, meta]) => meta.tier === 2).map(([feature]) => feature)
export const TIER3_FEATURES = Object.entries(FEATURE_META).filter(([, meta]) => meta.tier === 3).map(([feature]) => feature)
